name: coffea-env
channels:
  - conda-forge
dependencies:
  - conda-forge::python=3.9
  - numpy=1.23.5
  - coffea=0.7.21
  - dask
  - dask-awkward
  - dask-histogram
  - ndcctools
  - conda-pack
  - dill
  - xrootd
  - git
  - pyyaml
