name: coffea20250703
channels:
  - conda-forge
dependencies:
  - conda-forge::python=3.13
  - pip
  - conda-pack
  - ndcctools>=7.14.11
  - xrootd
  - setuptools>=72
  - numpy
  - dill
  - git
  - pyyaml
  - pytest
  - pip:
      - coffea==2025.7.3
      - awkward==2.8.7
