name: coffea202507
channels:
  - conda-forge
dependencies:
  - conda-forge::python=3.13
  - awkward=2.8.7
  - coffea=2025.7
  - numpy
  - ndcctools
  - conda-pack
  - dill
  - xrootd
  - git
  - pyyaml
