name: coffea202507
channels:
  - conda-forge
dependencies:
  - conda-forge::python
  - awkward=2.8.7
  - coffea=2025.7.3
  - numpy
  - coffea
  - ndcctools
  - conda-pack
  - dill
  - xrootd
  - git
  - pyyaml
