name: coffea2025
channels:
  - conda-forge
dependencies:
  - coffea=2025.7.3
  - awkward=2.8.7
  - pandas>=2.2,<2.3
  - hist=2.9.*
  - boost-histogram>=1.4
  - ndcctools
  - conda-pack
  - dill
  - xrootd
  - git
  - pyyaml
  - numpy=2.0.*
